capability_map = {
	'Customer Travel Experience' : ['Pre- and Post - Travel Experience', 'Check-In Desks Management', 'Gate Departure Management','Customer Airport Services'],
	'Pre- and Post - Travel Experience': ['Customer Products and Marketing', 'Sales', 'Customer Pre-Travel Experience', 'Access and Transportation', 'Customer Relations', 'Customer Loyalty Management'],
	'Check-In Desks Management': ['Luggage Acceptance', 'Passenger Information Management'],
	'Gate Departure Management': ['Outbound Flight Planning', 'Data Control Management', 'Passenger Boarding Management', 'Flight Closeout and Post Departure Management'],
	'Customer Airport Services': ['Retail Management', 'Lounge Services Management', 'Customer Special Needs Services Management'],
	'Customer Products and Marketing': [], 
	'Sales': [], 
	'Customer Pre-Travel Experience':[], 
	'Access and Transportation':[], 
	'Customer Relations':[], 
	'Customer Loyalty Management':[],
	'Luggage Acceptance':[], 
	'Passenger Information Management':[],
	'Outbound Flight Planning':[], 
	'Data Control Management':[], 
	'Passenger Boarding Management':[], 
	'Flight Closeout and Post Departure Management':[],
	'Outbound Flight Planning':[], 
	'Data Control Management':[], 
	'Passenger Boarding Management':[], 
	'Flight Closeout and Post Departure Management':[],
	'Retail Management':[], 
	'Lounge Services Management':[], 
	'Customer Special Needs Services Management':[]
}